config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "pages#home"
  
  resources :todos

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
    validates :name, presence: true
    validates :description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def home
	end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
    before_action :set_todo, only: [:edit, :update, :show, :destroy]
    
    def new
        @todo = Todo.new
        
    end
    
    def create
        @todo = Todo.new(todo_params)
        if  @todo.save
            flash[:notice] = "Todo correcto"
            redirect_to todo_path(@todo)
        else
            render 'new'
        end 
    end
    
    
    def show
        redirect_to todos_path
    end
    
    def edit
        
    end
    
    def update
       
       if @todo.update(todo_params)
           flash[:notice]= "Todo correcto"
           redirect_to todo_path(@todo)
       else
           render 'edit'
       end
    end
    
    def index
        @todos = Todo.all
    
    end
    
    def destroy
        
        @todo.destroy
        flash[:notice] = "Tarea eliminada"
        redirect_to todos_path
        
    end
    
    
    private
        
        def set_todo
        @todo = Todo.find(params[:id])
        end
    
        def todo_params
            params.require(:todo).permit(:name, :description)
        end 
    
    
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_messages.html.erb
<% flash.each do |name,msg| %>
          <ul>
            <li><%= msg %> </li>
          </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todos</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/messages" %>
    <div id="cont">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Home page projecto TODO</h1>

app/views/todos/_form.html.erb
<% if @todo.errors.any? %>
    <h2>Se encontraron los siguientes errores</h2>
    <ul>
        <% @todo.errors.full_messages.each do |msg| %>
        <li> <%=  msg %>  </li>      
        
        <% end%>

    </ul>
<% end %>
<%= form_for @todo do |f|  %>
    <p>
        <%= f.label  "Referencia"%> <br>
        <%= f.text_field :name %>
    </p>
    <p>
        <%= f.label "Descripción" %> <br>
        <%= f.text_area :description %>
    </p>

<p>
<%= f.submit "Enviar" %>
</p>


<% end %>
<%= link_to "Ir al inicio", todos_path(@todo) %>

app/views/todos/edit.html.erb
<h1>Editar</h1>
<%= render "form" %>

app/views/todos/index.html.erb
<h1>Tareas Pendientes SPV</h1>



<table>
<tr>
    <th>Referencia</th>
    <th>Descripción</th>
    <th class="b">Ver / Editar</th>
    
    <th class="b">Eliminar</th>
</tr>
    <% @todos.each do |todo| %>
    <tr>
        <td class="tarea"><%= todo.name.first(9) %></td>
        <td class="descrip"><%= todo.description.first(55) %></td>
        <td class="b"><%= link_to "X", edit_todo_path(todo) %></td>
        
        <td class="b"><%= link_to "X", todo_path(todo), method: :delete, data:{confirm: "Estas seguro?"}%></td>
         </td>
    </tr>
    
    <% end %>
    
</table>

<p class="lin">
    <%= link_to "Nueva Tarea", new_todo_path %>
</p>



app/views/todos/new.html.erb
<h1>Nueva Acción</h1>
<%= render "form" %>